name: PostgreSQL Service
on: push

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:latest
    env:
      POSTGRES_URI: 'postgres://postgres:postgres@postgres:5432/postgres'
      PORT: 8080
    services:
      postgres:
        image: monkeswag33/golang-postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: "1.18.0"
    - name: Install dependencies
      run: go mod tidy
    - name: Test script
      timeout-minutes: 5
      run: go test