name: Test Gin Code
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x, 1.15.x, 1.16.x, 1.17.x, 1.18.x]
    runs-on: ubuntu-latest
    name: Go ${{ matrix.go-version }}
    env:
      POSTGRES_URI: 'postgres://postgres:postgres@localhost:5432/postgres'
      PORT: 8080
      GIN_MODE: release
    services:
      postgres:
        image: monkeswag33/golang-postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - name: Install dependencies
      run: go mod tidy
    - name: Test script
      timeout-minutes: 5
      run: go test