name: Test Gin Code
on: [push, pull_request]

jobs:
  build:
    container: golang:latest
    strategy:
      matrix:
        go-version: [1.16.x, 1.17.x, 1.18.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: Go ${{ matrix.go-version }} On ${{ matrix.os }}
    env:
      POSTGRES_URI: 'postgres://postgres:postgres@postgres:5432/postgres'
      PORT: 8080
      GIN_MODE: release
    services:
      postgres:
        image: monkeswag33/golang-postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - name: Install dependencies
      run: go mod tidy
    - name: Test script
      timeout-minutes: 5
      run: go test